name: 'Code Scanning with CodeQL'

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**' # Don't build any tags
    paths-ignore:
      - '.github/**'
      - 'build.gradle.kts'
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'build.gradle.kts'

jobs:
  analyze_code:
    name: Analyze Code
    permissions:
      actions: read
      security-events: write
      contents: read
    uses: navikt/sosialhjelp-ci/.github/workflows/codeql_java.yml@v2